development:
  adapter: postgresql
  encoding: unicode
  database: iconomus
  pool: 5
  username: iconomus
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: iconomus_test
  pool: 5
  username: iconomus
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: iconomus
  pool: 5
  username: iconomus
  password:
